package com.zyc.travel.model.mapper;

import com.zyc.travel.model.dto.JTravelLine;
import com.zyc.travel.model.dto.JTravelLineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JTravelLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line
     *
     * @mbggenerated Wed Mar 01 17:53:37 CST 2017
     */
    int countByExample(JTravelLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line
     *
     * @mbggenerated Wed Mar 01 17:53:37 CST 2017
     */
    int deleteByExample(JTravelLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line
     *
     * @mbggenerated Wed Mar 01 17:53:37 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line
     *
     * @mbggenerated Wed Mar 01 17:53:37 CST 2017
     */
    int insert(JTravelLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line
     *
     * @mbggenerated Wed Mar 01 17:53:37 CST 2017
     */
    int insertSelective(JTravelLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line
     *
     * @mbggenerated Wed Mar 01 17:53:37 CST 2017
     */
    List<JTravelLine> selectByExample(JTravelLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line
     *
     * @mbggenerated Wed Mar 01 17:53:37 CST 2017
     */
    JTravelLine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line
     *
     * @mbggenerated Wed Mar 01 17:53:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") JTravelLine record, @Param("example") JTravelLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line
     *
     * @mbggenerated Wed Mar 01 17:53:37 CST 2017
     */
    int updateByExample(@Param("record") JTravelLine record, @Param("example") JTravelLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line
     *
     * @mbggenerated Wed Mar 01 17:53:37 CST 2017
     */
    int updateByPrimaryKeySelective(JTravelLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line
     *
     * @mbggenerated Wed Mar 01 17:53:37 CST 2017
     */
    int updateByPrimaryKey(JTravelLine record);
}