package com.zyc.travel.model.mapper;

import com.zyc.travel.model.dto.JTravelAgency;
import com.zyc.travel.model.dto.JTravelAgencyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JTravelAgencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int countByExample(JTravelAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int deleteByExample(JTravelAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int insert(JTravelAgency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int insertSelective(JTravelAgency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    List<JTravelAgency> selectByExample(JTravelAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    JTravelAgency selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") JTravelAgency record, @Param("example") JTravelAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int updateByExample(@Param("record") JTravelAgency record, @Param("example") JTravelAgencyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int updateByPrimaryKeySelective(JTravelAgency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int updateByPrimaryKey(JTravelAgency record);
}