package com.zyc.travel.model.mapper;

import com.zyc.travel.model.dto.JTravelAgencyAddress;
import com.zyc.travel.model.dto.JTravelAgencyAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JTravelAgencyAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency_address
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int countByExample(JTravelAgencyAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency_address
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int deleteByExample(JTravelAgencyAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency_address
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency_address
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int insert(JTravelAgencyAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency_address
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int insertSelective(JTravelAgencyAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency_address
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    List<JTravelAgencyAddress> selectByExample(JTravelAgencyAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency_address
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    JTravelAgencyAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency_address
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") JTravelAgencyAddress record, @Param("example") JTravelAgencyAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency_address
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int updateByExample(@Param("record") JTravelAgencyAddress record, @Param("example") JTravelAgencyAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency_address
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int updateByPrimaryKeySelective(JTravelAgencyAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_agency_address
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    int updateByPrimaryKey(JTravelAgencyAddress record);
}