package com.zyc.travel.model.mapper;

import com.zyc.travel.model.dto.JTravelLineExt;
import com.zyc.travel.model.dto.JTravelLineExtExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JTravelLineExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line_ext
     *
     * @mbggenerated Wed Mar 01 17:53:38 CST 2017
     */
    int countByExample(JTravelLineExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line_ext
     *
     * @mbggenerated Wed Mar 01 17:53:38 CST 2017
     */
    int deleteByExample(JTravelLineExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line_ext
     *
     * @mbggenerated Wed Mar 01 17:53:38 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line_ext
     *
     * @mbggenerated Wed Mar 01 17:53:38 CST 2017
     */
    int insert(JTravelLineExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line_ext
     *
     * @mbggenerated Wed Mar 01 17:53:38 CST 2017
     */
    int insertSelective(JTravelLineExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line_ext
     *
     * @mbggenerated Wed Mar 01 17:53:38 CST 2017
     */
    List<JTravelLineExt> selectByExampleWithBLOBs(JTravelLineExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line_ext
     *
     * @mbggenerated Wed Mar 01 17:53:38 CST 2017
     */
    List<JTravelLineExt> selectByExample(JTravelLineExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line_ext
     *
     * @mbggenerated Wed Mar 01 17:53:38 CST 2017
     */
    JTravelLineExt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line_ext
     *
     * @mbggenerated Wed Mar 01 17:53:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") JTravelLineExt record, @Param("example") JTravelLineExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line_ext
     *
     * @mbggenerated Wed Mar 01 17:53:38 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") JTravelLineExt record, @Param("example") JTravelLineExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line_ext
     *
     * @mbggenerated Wed Mar 01 17:53:38 CST 2017
     */
    int updateByExample(@Param("record") JTravelLineExt record, @Param("example") JTravelLineExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line_ext
     *
     * @mbggenerated Wed Mar 01 17:53:38 CST 2017
     */
    int updateByPrimaryKeySelective(JTravelLineExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_travel_line_ext
     *
     * @mbggenerated Wed Mar 01 17:53:38 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(JTravelLineExt record);
}