package com.zyc.travel.model.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class JTravelAgency implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.id
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.travel_name
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    private String travelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.travel_tel
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    private String travelTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.travel_phone
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    private String travelPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.travel_remark
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    private String travelRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.travel_status
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    private Integer travelStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.travel_type
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    private Integer travelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.travel_balance
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    private BigDecimal travelBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.create_date
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table j_travel_agency
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.id
     *
     * @return the value of j_travel_agency.id
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.id
     *
     * @param id the value for j_travel_agency.id
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.travel_name
     *
     * @return the value of j_travel_agency.travel_name
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public String getTravelName() {
        return travelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.travel_name
     *
     * @param travelName the value for j_travel_agency.travel_name
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public void setTravelName(String travelName) {
        this.travelName = travelName == null ? null : travelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.travel_tel
     *
     * @return the value of j_travel_agency.travel_tel
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public String getTravelTel() {
        return travelTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.travel_tel
     *
     * @param travelTel the value for j_travel_agency.travel_tel
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public void setTravelTel(String travelTel) {
        this.travelTel = travelTel == null ? null : travelTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.travel_phone
     *
     * @return the value of j_travel_agency.travel_phone
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public String getTravelPhone() {
        return travelPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.travel_phone
     *
     * @param travelPhone the value for j_travel_agency.travel_phone
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public void setTravelPhone(String travelPhone) {
        this.travelPhone = travelPhone == null ? null : travelPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.travel_remark
     *
     * @return the value of j_travel_agency.travel_remark
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public String getTravelRemark() {
        return travelRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.travel_remark
     *
     * @param travelRemark the value for j_travel_agency.travel_remark
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public void setTravelRemark(String travelRemark) {
        this.travelRemark = travelRemark == null ? null : travelRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.travel_status
     *
     * @return the value of j_travel_agency.travel_status
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public Integer getTravelStatus() {
        return travelStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.travel_status
     *
     * @param travelStatus the value for j_travel_agency.travel_status
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public void setTravelStatus(Integer travelStatus) {
        this.travelStatus = travelStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.travel_type
     *
     * @return the value of j_travel_agency.travel_type
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public Integer getTravelType() {
        return travelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.travel_type
     *
     * @param travelType the value for j_travel_agency.travel_type
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public void setTravelType(Integer travelType) {
        this.travelType = travelType;
    }

    public BigDecimal getTravelBalance() {
        return travelBalance;
    }

    public void setTravelBalance(BigDecimal travelBalance) {
        this.travelBalance = travelBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.create_date
     *
     * @return the value of j_travel_agency.create_date
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.create_date
     *
     * @param createDate the value for j_travel_agency.create_date
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}