package com.zyc.travel.model.dto;

import java.io.Serializable;

public class JTravelAgencyAddress implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency_address.id
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency_address.travel_id
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    private Integer travelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency_address.county
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency_address.detailed_address
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    private String detailedAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table j_travel_agency_address
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency_address.id
     *
     * @return the value of j_travel_agency_address.id
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency_address.id
     *
     * @param id the value for j_travel_agency_address.id
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency_address.travel_id
     *
     * @return the value of j_travel_agency_address.travel_id
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public Integer getTravelId() {
        return travelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency_address.travel_id
     *
     * @param travelId the value for j_travel_agency_address.travel_id
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public void setTravelId(Integer travelId) {
        this.travelId = travelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency_address.county
     *
     * @return the value of j_travel_agency_address.county
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency_address.county
     *
     * @param county the value for j_travel_agency_address.county
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency_address.detailed_address
     *
     * @return the value of j_travel_agency_address.detailed_address
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public String getDetailedAddress() {
        return detailedAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency_address.detailed_address
     *
     * @param detailedAddress the value for j_travel_agency_address.detailed_address
     *
     * @mbggenerated Wed Jan 18 14:59:45 CST 2017
     */
    public void setDetailedAddress(String detailedAddress) {
        this.detailedAddress = detailedAddress == null ? null : detailedAddress.trim();
    }
}