package com.zyc.travel.model.dto;

import java.io.Serializable;
import java.util.Date;

public class JTravelAgency implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.id
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.travel_name
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    private String travelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.travel_tel
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    private String travelTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.travel_phone
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    private String travelPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.travel_remark
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    private String travelRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.travel_status
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    private Integer travelStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.travel_type
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    private Integer travelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.travel_balance
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    private Long travelBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.travel_area
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    private String travelArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.travel_address_detail
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    private String travelAddressDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.business_license_url
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    private String businessLicenseUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.procedure_prove_url
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    private String procedureProveUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.username
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.password
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.create_date
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency.update_date
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table j_travel_agency
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.id
     *
     * @return the value of j_travel_agency.id
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.id
     *
     * @param id the value for j_travel_agency.id
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.travel_name
     *
     * @return the value of j_travel_agency.travel_name
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public String getTravelName() {
        return travelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.travel_name
     *
     * @param travelName the value for j_travel_agency.travel_name
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public void setTravelName(String travelName) {
        this.travelName = travelName == null ? null : travelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.travel_tel
     *
     * @return the value of j_travel_agency.travel_tel
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public String getTravelTel() {
        return travelTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.travel_tel
     *
     * @param travelTel the value for j_travel_agency.travel_tel
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public void setTravelTel(String travelTel) {
        this.travelTel = travelTel == null ? null : travelTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.travel_phone
     *
     * @return the value of j_travel_agency.travel_phone
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public String getTravelPhone() {
        return travelPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.travel_phone
     *
     * @param travelPhone the value for j_travel_agency.travel_phone
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public void setTravelPhone(String travelPhone) {
        this.travelPhone = travelPhone == null ? null : travelPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.travel_remark
     *
     * @return the value of j_travel_agency.travel_remark
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public String getTravelRemark() {
        return travelRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.travel_remark
     *
     * @param travelRemark the value for j_travel_agency.travel_remark
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public void setTravelRemark(String travelRemark) {
        this.travelRemark = travelRemark == null ? null : travelRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.travel_status
     *
     * @return the value of j_travel_agency.travel_status
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public Integer getTravelStatus() {
        return travelStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.travel_status
     *
     * @param travelStatus the value for j_travel_agency.travel_status
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public void setTravelStatus(Integer travelStatus) {
        this.travelStatus = travelStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.travel_type
     *
     * @return the value of j_travel_agency.travel_type
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public Integer getTravelType() {
        return travelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.travel_type
     *
     * @param travelType the value for j_travel_agency.travel_type
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public void setTravelType(Integer travelType) {
        this.travelType = travelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.travel_balance
     *
     * @return the value of j_travel_agency.travel_balance
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public Long getTravelBalance() {
        return travelBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.travel_balance
     *
     * @param travelBalance the value for j_travel_agency.travel_balance
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public void setTravelBalance(Long travelBalance) {
        this.travelBalance = travelBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.travel_area
     *
     * @return the value of j_travel_agency.travel_area
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public String getTravelArea() {
        return travelArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.travel_area
     *
     * @param travelArea the value for j_travel_agency.travel_area
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public void setTravelArea(String travelArea) {
        this.travelArea = travelArea == null ? null : travelArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.travel_address_detail
     *
     * @return the value of j_travel_agency.travel_address_detail
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public String getTravelAddressDetail() {
        return travelAddressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.travel_address_detail
     *
     * @param travelAddressDetail the value for j_travel_agency.travel_address_detail
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public void setTravelAddressDetail(String travelAddressDetail) {
        this.travelAddressDetail = travelAddressDetail == null ? null : travelAddressDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.business_license_url
     *
     * @return the value of j_travel_agency.business_license_url
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public String getBusinessLicenseUrl() {
        return businessLicenseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.business_license_url
     *
     * @param businessLicenseUrl the value for j_travel_agency.business_license_url
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public void setBusinessLicenseUrl(String businessLicenseUrl) {
        this.businessLicenseUrl = businessLicenseUrl == null ? null : businessLicenseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.procedure_prove_url
     *
     * @return the value of j_travel_agency.procedure_prove_url
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public String getProcedureProveUrl() {
        return procedureProveUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.procedure_prove_url
     *
     * @param procedureProveUrl the value for j_travel_agency.procedure_prove_url
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public void setProcedureProveUrl(String procedureProveUrl) {
        this.procedureProveUrl = procedureProveUrl == null ? null : procedureProveUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.username
     *
     * @return the value of j_travel_agency.username
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.username
     *
     * @param username the value for j_travel_agency.username
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.password
     *
     * @return the value of j_travel_agency.password
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.password
     *
     * @param password the value for j_travel_agency.password
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.create_date
     *
     * @return the value of j_travel_agency.create_date
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.create_date
     *
     * @param createDate the value for j_travel_agency.create_date
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency.update_date
     *
     * @return the value of j_travel_agency.update_date
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency.update_date
     *
     * @param updateDate the value for j_travel_agency.update_date
     *
     * @mbggenerated Mon Jan 23 18:25:02 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}