package com.zyc.travel.model.dto;

import java.io.Serializable;
import java.util.Date;

public class JTravelAgencyContacts implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency_contacts.id
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency_contacts.travel_id
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    private Integer travelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency_contacts.contacts_name
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    private String contactsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency_contacts.contacts_phone
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    private String contactsPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency_contacts.contacts_weixin
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    private String contactsWeixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency_contacts.contacts_qq
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    private String contactsQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency_contacts.contacts_position
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    private String contactsPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency_contacts.status
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency_contacts.create_date
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_travel_agency_contacts.update_date
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table j_travel_agency_contacts
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency_contacts.id
     *
     * @return the value of j_travel_agency_contacts.id
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency_contacts.id
     *
     * @param id the value for j_travel_agency_contacts.id
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency_contacts.travel_id
     *
     * @return the value of j_travel_agency_contacts.travel_id
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public Integer getTravelId() {
        return travelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency_contacts.travel_id
     *
     * @param travelId the value for j_travel_agency_contacts.travel_id
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public void setTravelId(Integer travelId) {
        this.travelId = travelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency_contacts.contacts_name
     *
     * @return the value of j_travel_agency_contacts.contacts_name
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public String getContactsName() {
        return contactsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency_contacts.contacts_name
     *
     * @param contactsName the value for j_travel_agency_contacts.contacts_name
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public void setContactsName(String contactsName) {
        this.contactsName = contactsName == null ? null : contactsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency_contacts.contacts_phone
     *
     * @return the value of j_travel_agency_contacts.contacts_phone
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public String getContactsPhone() {
        return contactsPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency_contacts.contacts_phone
     *
     * @param contactsPhone the value for j_travel_agency_contacts.contacts_phone
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public void setContactsPhone(String contactsPhone) {
        this.contactsPhone = contactsPhone == null ? null : contactsPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency_contacts.contacts_weixin
     *
     * @return the value of j_travel_agency_contacts.contacts_weixin
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public String getContactsWeixin() {
        return contactsWeixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency_contacts.contacts_weixin
     *
     * @param contactsWeixin the value for j_travel_agency_contacts.contacts_weixin
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public void setContactsWeixin(String contactsWeixin) {
        this.contactsWeixin = contactsWeixin == null ? null : contactsWeixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency_contacts.contacts_qq
     *
     * @return the value of j_travel_agency_contacts.contacts_qq
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public String getContactsQq() {
        return contactsQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency_contacts.contacts_qq
     *
     * @param contactsQq the value for j_travel_agency_contacts.contacts_qq
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public void setContactsQq(String contactsQq) {
        this.contactsQq = contactsQq == null ? null : contactsQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency_contacts.contacts_position
     *
     * @return the value of j_travel_agency_contacts.contacts_position
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public String getContactsPosition() {
        return contactsPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency_contacts.contacts_position
     *
     * @param contactsPosition the value for j_travel_agency_contacts.contacts_position
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public void setContactsPosition(String contactsPosition) {
        this.contactsPosition = contactsPosition == null ? null : contactsPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency_contacts.status
     *
     * @return the value of j_travel_agency_contacts.status
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency_contacts.status
     *
     * @param status the value for j_travel_agency_contacts.status
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency_contacts.create_date
     *
     * @return the value of j_travel_agency_contacts.create_date
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency_contacts.create_date
     *
     * @param createDate the value for j_travel_agency_contacts.create_date
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_travel_agency_contacts.update_date
     *
     * @return the value of j_travel_agency_contacts.update_date
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_travel_agency_contacts.update_date
     *
     * @param updateDate the value for j_travel_agency_contacts.update_date
     *
     * @mbggenerated Wed Mar 01 13:29:33 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}